Repository VLD-dev-team/Social-Co2, pull requests merged in 2024-04, with the labels that each got.

#9 merge: Suite de l'intégration des LeaderBoard, des ReccurentsActivities et intégration des fonctionnalités de post et de feed de l'API
  application/social_co2/lib/classes/activity.dart
  application/social_co2/lib/classes/post.dart
  application/social_co2/lib/collections/activitiesData.dart
  application/social_co2/lib/main.dart
  application/social_co2/lib/providers/FeedProvider.dart
  application/social_co2/lib/providers/MakePostProvider.dart
  application/social_co2/lib/providers/SCO2ReportProvider.dart
  application/social_co2/lib/providers/UserActivitiesProvider.dart
  application/social_co2/lib/providers/UserSCO2DataProvider.dart
  application/social_co2/lib/screens/adaptativeContainers/WebAdaptativeContainer.dart
  application/social_co2/lib/screens/dialogs/dialogMood.dart
  application/social_co2/lib/screens/dialogs/dialogNewActivity.dart
  application/social_co2/lib/screens/mainScreens/HomeScreen.dart
  application/social_co2/lib/screens/mainScreens/SCO2ReportScreen.dart
  application/social_co2/lib/screens/widgets/ActivitiesList.dart
  application/social_co2/lib/screens/widgets/CallToPost.dart
  application/social_co2/lib/screens/widgets/CardMoreInformations.dart
  application/social_co2/lib/screens/widgets/Feed.dart
  application/social_co2/lib/screens/widgets/FeedPost.dart
  application/social_co2/lib/screens/widgets/LeaderBoardWidget.dart
  application/social_co2/lib/screens/widgets/ScoreQuickOverview.dart
  application/social_co2/lib/styles/webDrawersStyle.dart
  application/social_co2/lib/utils/requestsService.dart
Labels: bug, enhancement

#14 Merge: Avancée intégration de l'API
  server/README.md
  server/apiroutes/activity.js
  server/apiroutes/friends.js
  server/apiroutes/leaderboard.js
  server/apiroutes/rapport.js
  server/apiroutes/social.js
  server/apiroutes/user.js
  server/app.js
  server/schemaAPI/GestionAPI.drawio
Labels: bug, enhancement

#10 Merge: Création de la page Web publique
  .vscode/launch.json
  website/README
  website/sco2-react/.eslintrc.json
  website/sco2-react/.gitignore
  website/sco2-react/README.md
  website/sco2-react/app/assets/jungle.svg
  website/sco2-react/app/assets/logo_sco2.svg
  website/sco2-react/app/components/Button.jsx
  website/sco2-react/app/components/Menu.jsx
  website/sco2-react/app/components/Menu2.jsx
  website/sco2-react/app/components/Menu3.jsx
  website/sco2-react/app/components/Menu4.jsx
  website/sco2-react/app/globals.css
  website/sco2-react/app/layout.tsx
  website/sco2-react/app/page.tsx
  website/sco2-react/next.config.mjs
  website/sco2-react/package-lock.json
  website/sco2-react/package.json
  website/sco2-react/postcss.config.js
  website/sco2-react/public/acceuil-1.png
  website/sco2-react/public/banner.png
  website/sco2-react/public/image1.png
  website/sco2-react/public/logo.png
  website/sco2-react/public/messagerie1.png
  website/sco2-react/tailwind.config.ts
  website/sco2-react/tsconfig.json
Labels: enhancement

#39 Dernière PR avant déploiement
  application/social_co2/README.md
  application/social_co2/lib/classes/activity.dart
  application/social_co2/lib/classes/post.dart
  application/social_co2/lib/providers/FeedProvider.dart
  application/social_co2/lib/providers/MakePostProvider.dart
  application/social_co2/lib/providers/SCO2ReportProvider.dart
  application/social_co2/lib/providers/UserActivitiesProvider.dart
  application/social_co2/lib/screens/adaptativeContainers/WebAdaptativeContainer.dart
  application/social_co2/lib/screens/authScreen.dart
  application/social_co2/lib/screens/dialogs/dialogComments.dart
  application/social_co2/lib/screens/dialogs/dialogNewActivity.dart
  application/social_co2/lib/screens/dialogs/dialogPostActivities.dart
  application/social_co2/lib/screens/mainScreens/ActivitiesScreen.dart
  application/social_co2/lib/screens/mainScreens/HomeScreen.dart
  application/social_co2/lib/screens/mainScreens/LeaderBoardScreen.dart
  application/social_co2/lib/screens/mainScreens/ReportScreen.dart
  application/social_co2/lib/screens/mainScreens/SettingsScreen.dart
  application/social_co2/lib/screens/widgets/ActivitiesList.dart
  application/social_co2/lib/screens/widgets/CallToPost.dart
  application/social_co2/lib/screens/widgets/CardActivityList.dart
  application/social_co2/lib/screens/widgets/CardMoreInformations.dart
  application/social_co2/lib/screens/widgets/FeedPost.dart
  application/social_co2/lib/screens/widgets/ScoreQuickOverview.dart
  application/social_co2/lib/utils/requestsService.dart
Labels: bug, enhancement

#56 doc: Création documentation utilisateur universitaire
  Documentation utilisateur.md
Labels: documentation
